../tests/t00_test_case_simple.v
../tests/t01_read_write_TDR.v
../tests/t02_read_write_TCR.v
../tests/t03_read_write_TSR.v
../tests/t04_non_exist_address.v
../tests/t05_countdown_underflow_pclk2.v
../tests/t06_countdown_underflow_pclk4.v
../tests/t07_countdown_underflow_pclk8.v
../tests/t08_countdown_underflow_pclk16.v
../tests/t09_countup_overflow_pclk2.v
../tests/t10_countup_overflow_pclk4.v
../tests/t11_countup_overflow_pclk8.v
../tests/t12_countup_overflow_pclk16.v
../tests/t13_pause_countdown_pclk2.v
../tests/t14_pause_countup_pclk2.v
../tests/t15_countdown_reload_countdown_pclk2.v
../tests/t16_countdown_reset_countdown_pclk2.v
../tests/t17_countup_reload_countup_pclk2.v
../tests/t18_countup_reset_countup_pclk2.v
../tests/t19_fake_check_flow.v